name: ci

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install deno
        uses: denoland/setup-deno@v2

      - name: Run
        run: deno run --allow-read --allow-env --allow-net main.ts
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
